title: NeuroPedia
description: Neuroimaging resource based on Radiopaedia.org
theme: just-the-docs

url: https://gmadevs.github.io/neuropedia

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/gmadevs/neuropedia
